// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameScrapeClient is the client API for GameScrape service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameScrapeClient interface {
}

type gameScrapeClient struct {
	cc grpc.ClientConnInterface
}

func NewGameScrapeClient(cc grpc.ClientConnInterface) GameScrapeClient {
	return &gameScrapeClient{cc}
}

// GameScrapeServer is the server API for GameScrape service.
// All implementations must embed UnimplementedGameScrapeServer
// for forward compatibility
type GameScrapeServer interface {
	mustEmbedUnimplementedGameScrapeServer()
}

// UnimplementedGameScrapeServer must be embedded to have forward compatible implementations.
type UnimplementedGameScrapeServer struct {
}

func (UnimplementedGameScrapeServer) mustEmbedUnimplementedGameScrapeServer() {}

// UnsafeGameScrapeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameScrapeServer will
// result in compilation errors.
type UnsafeGameScrapeServer interface {
	mustEmbedUnimplementedGameScrapeServer()
}

func RegisterGameScrapeServer(s grpc.ServiceRegistrar, srv GameScrapeServer) {
	s.RegisterService(&GameScrape_ServiceDesc, srv)
}

// GameScrape_ServiceDesc is the grpc.ServiceDesc for GameScrape service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameScrape_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GameScrape",
	HandlerType: (*GameScrapeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "gamelist.proto",
}
